Deprecation of "rU"
biopython/biopython.github.io pull request #186
Opened 2021-03-01 17:24 UTC by recepcanaltinbag

"rU" was deprecated in Python 3.4, so it is not needed. For Python 3.4+, "rU" will give deprecation error.

2021-03-01 17:49 UTC, peterjc commented
You're right this can be improved. We currently only support Python 3.6 onwards, so you can make this even simpler by not talking about universal read lines mode at all (it is the default now).

2021-03-01 23:00 UTC, peterjc requested changes
The change looks good, just a cosmetic issue of removing trailing spaces.

2021-03-02 00:15 UTC, recepcanaltinbag commented on wiki/SeqIO.md
> +function `open`. The `with`- statement makes sure that the file is properly
Sorry about that, I hope it is fine now

2021-03-02 00:43 UTC, merged

2021-03-02 00:43 UTC, peterjc commented
Perfect, thank you.